repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.2.1'
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.3.1'
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.1'
    hooks:
      - id: mypy
        args: ['--strict']
        additional_dependencies:
          - types-setuptools
          - typing_extensions
          - aiohttp
