repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.2.1'
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'
    hooks:
    -   id: autopep8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
      - id: mypy
        # https://github.com/pre-commit/mirrors-mypy:
        # Note that using the --install-types is problematic
        additional_dependencies:
          - types-setuptools
          - typing_extensions
          - aiohttp
        args: ['--strict']
